# Generated by Django 2.1.7 on 2019-04-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsanalysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('time', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=500)),
                ('digest', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('analysis', models.CharField(max_length=20)),
            ],
        ),
    ]
