# Generated by Django 2.1.7 on 2019-04-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsanalysis', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='sina_weibo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=200)),
                ('star_num', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('link', models.CharField(max_length=500)),
            ],
        ),
    ]
