# Generated by Django 2.1.7 on 2019-04-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsanalysis', '0003_sina_weibo'),
    ]

    operations = [
        migrations.CreateModel(
            name='weibohot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=100)),
                ('star_num', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('link', models.CharField(max_length=200)),

            ],
        ),
    ]
