# Generated by Django 2.1.7 on 2019-04-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsanalysis', '0005_toutiao'),
    ]

    operations = [
        migrations.CreateModel(
            name='news163_digit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('time', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=500)),
                ('digest', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('analysis', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='news163_era',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('time', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=500)),
                ('digest', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('analysis', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='news163_fore',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('time', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=500)),
                ('digest', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('analysis', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='news163_fund',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('time', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=500)),
                ('digest', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('analysis', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='news163_sport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('time', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=500)),
                ('digest', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('analysis', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='news163_star',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('time', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=500)),
                ('digest', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('analysis', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='news163_stock',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('time', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=500)),
                ('digest', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('analysis', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='news163_tech',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('time', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=500)),
                ('digest', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('analysis', models.CharField(max_length=20)),
            ],
        ),
    ]
