# Generated by Django 2.1.7 on 2019-04-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsanalysis', '0006_news163_digit_news163_era_news163_fore_news163_fund_news163_sport_news163_star_news163_stock_news163'),
    ]

    operations = [
        migrations.CreateModel(
            name='weibohot_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
