# Generated by Django 2.1.7 on 2019-05-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsanalysis', '0007_weibohot_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sina_weibo',
            name='analysis',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
