# Generated by Django 2.1.7 on 2019-05-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsanalysis', '0008_sina_weibo_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sina_weibo',
            name='analysis',
            field=models.IntegerField(),
        ),
    ]
