# Generated by Django 2.1.7 on 2019-05-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsanalysis', '0009_auto_20190501_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sina_weibo',
            name='analysis',
        ),
    ]
