# Generated by Django 2.1.7 on 2019-05-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsanalysis', '0010_remove_sina_weibo_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibohot',
            name='analysis',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
